### PR TITLE
Fix relative path

### PR DESCRIPTION
**Pull request by MattiSG**
```
julia> Pkg.test("OpenFiscaFrance")

INFO: Testing OpenFiscaFrance
ERROR: unable to read directory test/formulas: No such file or directory
 in systemerror at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in readdir at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in test_formulas at /Users/sgmap/.julia/v0.3/OpenFiscaFrance/test/test_formulas.jl:27
 in include at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /opt/homebrew-cask/Caskroom/julia/0.3.8/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/sgmap/.julia/v0.3/OpenFiscaFrance/test/test_formulas.jl, in expression starting on line 90
while loading /Users/sgmap/.julia/v0.3/OpenFiscaFrance/test/runtests.jl, in expression starting on line 38
```

### CODE REVIEW

**Comment by MattiSG** [comment]
This should be double-checked, I have other failures that prevent me from knowing if this fix works properly.

**Comment by MattiSG** [comment]
Ok, I could test it with `Pkg.test(pwd())`, this works and reveals a `ERROR: function to_float does not accept keyword arguments`.

**Comment by cbenz** [comment]
I fixed like that: 629d11a552b4ee2a6a504a41cbf7512746f8e256

**Comment by MattiSG** [comment]
Cool!  :)

**Pull request closed without merging**
